version: '3'
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: cXGiKi9Otf3xtIbPGHp9
      MINIO_SECRET_KEY: bDpmvYrjsaqPigTazyB9SVQGFxtk9FJeSFVp4nlb
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      minio:
        condition: service_healthy
    environment:
      S3_ENDPOINT: minio:9000
      S3_ACCESS_KEY: cXGiKi9Otf3xtIbPGHp9
      S3_SECRET_KEY: bDpmvYrjsaqPigTazyB9SVQGFxtk9FJeSFVp4nlb
